#服务端口配置
server:
   port: 8081
#Spring数据源配置名称配置
spring:
   application:
      name: Generator
   datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://120.77.253.118:3306/erp-iam?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456
jboot:
   generator:
      enabled: true
   package: org.jboot.generator
   java: src/main/java
   resource: src/main/resources
mybatis:
   mapper-locations: classpath:mappers/*.xml
   type-aliases-package: org.jboot.generator.entity
   configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
swagger:
   enabled: true
   package: org.jboot.generator
pagehelper:
   helper-dialect: mysql
   reasonable: true
   support-methods-arguments: true
   params: count=countsql