#服务端口配置
server:
   port: 8081
#Spring数据源配置名称配置
spring:
   application:
      name: Generator
   datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://localhost:3306/scott?serverTimezone=UTC
      username: root
      password: 123456
jboot:
   package: org.jboot.generator
   java: src/main/java
   resource: src/main/resources
#mybatis扫描配置
mybatis:
   mapper-locations: classpath:mappers/*.xml
   type-aliases-package: org.jboot.generator.entity
   configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
###swagger ui 配置
swagger:
   enabled: true
   package: org.jboot.generator
###分頁插件使用配置   
pagehelper:
   helperDialect: mysql
   reasonable: true
   supportMethodsArguments: true
   params: count=countSql