server:
   port: 8081
spring:
   application:
      name: Generator
   datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://127.0.0.1:3306/scott?serverTimezone=UTC
      username: root
      password: welcome@123
mybatis:
   mapper-locations: classpath:mappers/*.xml
   type-aliases-package: com.frame.business.entity
swagger:
   enabled: true
   package: com.frame.business